modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="create_emf_compat"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
logoFile = "icon.png"
description='''
${mod_description}
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.create_emf_compat]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.create_emf_compat]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.create_emf_compat]]
modId="create"
type="required"
versionRange="[6.0.10,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.create_emf_compat]]
modId="entity_model_features"
type="required"
versionRange="[3.2.4,)"
ordering="AFTER"
side="CLIENT"
